check:
  - thoth-build
build:
  build-stratergy: "Dockerfile"
  registry: "quay.io"
  registry-org: "thoth-station"
  registry-project: "nepthys"
  registry-secret: "thoth-station-thoth-pusher-secret"
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "nepthys"
  overlay-contextpath: "nepthys/overlays/ocp/imagestreamtag.yaml"
