host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
  - name: rhel:8
    operating_system:
      name: rhel
      version: "8"
    python_version: "3.6"
    recommendation_type: latest

managers:
  - name: info
  - name: version
    configuration:
      maintainers:
        - goern
        - fridex
        - harshad16
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
