---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "This is Nepthys BuildConfig"
    openshift.io/display-name: "Thoth: Nepthys BuildConfig"
    tags: "thoth,ai-stacks,nepthys"
    template.openshift.io/documentation-url: "https://github.com/Thoth-Station/"
    template.openshift.io/long-description: "This template defines resources needed to deploy Thoth Nepthys to OpenShift.\n"
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    version: "1.0.0"
  labels:
    app: thoth
    component: nepthys
    template: nepthys-buildconfig
  name: nepthys-buildconfig

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: thoth
        component: nepthys
      name: nepthys-job
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "nepthys-job:${IMAGE_STREAM_TAG}"
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 500m
          memory: 512Mi
      runPolicy: Serial
      source:
        git:
          ref: "${GITHUB_REF}"
          uri: "${GITHUB_URL}"
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: Dockerfile
          noCache: true
        env:
          - name: ENABLE_PIPENV
            value: "1"
          - name: UPGRADE_PIP_TO_LATEST
            value: ""
        type: Docker
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret

  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: s2i-thoth-ubi8-py36-nepthys
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      labels:
        app: thoth
        component: nepthys
    spec:
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      output:
        to:
          kind: ImageStreamTag
          name: "s2i-thoth-ubi8-py36-nepthys:${IMAGE_STREAM_TAG}"
      source:
        dockerfile: |
          FROM s2i-thoth-ubi8-py36:latest
          ENV LANG=en_US.UTF-8
          USER 0
          RUN dnf install -y graphviz
          USER 1001
      strategy:
        type: Docker
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py36:latest
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
        - type: Generic
          generic:
            secretReference:
              name: generic-webhook-secret

parameters:
  - description: "Git repository for Thoth's Nepthys"
    displayName: "Thoth Nepthys git repository"
    name: GITHUB_URL
    required: true
    value: "https://github.com/thoth-station/nepthys"

  - description: "Git repository for Thoth's Nepthys Job"
    displayName: "Thoth Nepyths git reference"
    name: GITHUB_REF
    required: true
    value: master

  - description: "Tag of the output ImageStream the resulting container image should go to"
    displayName: "ImageStream Tag"
    name: IMAGE_STREAM_TAG
    required: true
    value: latest
